### ISSUE TITLE
Upload button does not work

### ISSUE THREAD

**Issue by Zansai** [hrvoje-fadiga/access-marketmind-testing#4]
For a user that has a shared folder, the upload button does not work. 

Go to this link: http://engineering.marketmind.at/accessmm/Mixed/AccountExternal/Access/edc9e971a7985e0a3dc39370cd74c8d5

use rickboender1@gmail.com and try to upload a file via the button

**Comment by Zansai** [comment]
Oooh, now I see it. You first need to select a file and then upload it. Isn't that a bit double?

**Comment by hrvoje-fadiga** [comment]
Improved!
